
# .travis.yaml
#
# This file is part of the NEST example module.
#
# Copyright (C) 2004 The NEST Initiative
#
# NEST is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# NEST is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NEST.  If not, see <http://www.gnu.org/licenses/>.


# This is the Travis CI top-level script to setup and run the build
# and test environment for the NEST example module.

language: python

sudo: required 
dist: bionic

stages:
   - Linux
   - macOS

jobs:
  include:
    - stage: Linux
      python: 3.8.2
    - stage: macOS
      os: osx
      osx_image: xcode12   # Python 3.8.3 running on macOS 10.15.5
      language: shell      # language 'python' results in errors on macOS

addons:
  apt:
    sources:
      - *BASE_SOURCES
    packages:
      - *BASE_PACKAGES
      - gcc-8
      - g++-8
      - clang-7
      - build-essential
      - cmake
      - libltdl-dev
      - libreadline6-dev
      - libncurses5-dev
      - libgsl0-dev
      - python3-all-dev
      - openmpi-bin
      - libopenmpi-dev
      - libboost-filesystem-dev
      - libboost-regex-dev
      - libboost-wave-dev
      - libboost-python-dev
      - libboost-program-options-dev
      - libboost-test-dev
      - python3-mpi4py
      - libsfml-dev
      - llvm-9-dev

before_install:
  - export SOURCEDIR=$PWD
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      ls -lh /usr/bin/g++*
      ls -lh /usr/bin/gcc*
      ls -lh /usr/bin/c++*
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 20
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 10
      sudo update-alternatives --auto g++
      sudo update-alternatives --list g++
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 20
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 10
      sudo update-alternatives --auto gcc
      sudo update-alternatives --list gcc
      sudo update-alternatives --list c++
      sudo update-alternatives --auto c++
      g++ --version
      /usr/bin/c++ --version
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew --version
      brew update
      brew info python
      export PATH="/usr/local/opt/python/libexec/bin:$PATH"  # To use homebrew's Python
      brew tap brewsci/science
      brew tap brewsci/bio
      brew install coreutils gsl open-mpi automake autoconf libtool
      brew unlink gcc
      brew install gcc@8
      brew link gcc@8
      brew list
      brew leaves
      brew cask list
    fi
  - pip install cython scipy matplotlib numpy==1.16.5

before_script:
  - chmod +x travis_build.sh
  - cd ${SOURCEDIR}

script:
  - set -o pipefail
  - echo ${PWD}
  - ./travis_build.sh
